### ISSUE TITLE
Sentence is not correct ?

### ISSUE THREAD

**Issue by tnuanchuay** [cmry/cmry.github.io#1]
![image](https://user-images.githubusercontent.com/7426678/52217496-1f4b2000-28cb-11e9-906e-b293568834e4.png)

Hi, I am not sure mine's right. but I think tennis value is far more than soccer and AI, so I should be fixed to be 
`However, see how it's also closer to soccer than AI`

**Comment by cmry** [comment]
Should be soccer indeed, thanks for spotting that one!

-------- Original Message --------
